-- Table: auth_user
CREATE TABLE auth_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR2(128) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE NULL,
    is_superuser NUMBER(1) NOT NULL,
    username VARCHAR2(150) NOT NULL UNIQUE,
    first_name VARCHAR2(150) NOT NULL,
    last_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    is_staff NUMBER(1) NOT NULL,
    is_active NUMBER(1) NOT NULL,
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Table: my_app_wines
CREATE TABLE my_app_wines (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Type VARCHAR2(100) NOT NULL,
    Year NUMBER NULL,
    Grapes VARCHAR2(100) NULL,
    Country VARCHAR2(100) NOT NULL,
    Region VARCHAR2(100) NULL,
    Price NUMBER(6, 2) NULL,
    Description CLOB NOT NULL,
    Qty NUMBER NULL,
    image VARCHAR2(100) NULL
);

-- Table: my_app_spirits
CREATE TABLE my_app_spirits (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type VARCHAR2(100) NOT NULL,
    Name VARCHAR2(100) NOT NULL,
    Style VARCHAR2(100) NULL,
    AlcLvl NUMBER NOT NULL,
    Price NUMBER(6, 2) NULL,
    Qty NUMBER NULL,
    image VARCHAR2(100) NULL
);

-- Table: my_app_cart
CREATE TABLE my_app_cart (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE REFERENCES auth_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Table: my_app_cartitem
CREATE TABLE my_app_cartitem (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id NUMBER NOT NULL REFERENCES my_app_cart(id) ON DELETE CASCADE,
    wine_id NUMBER NULL REFERENCES my_app_wines(ID) ON DELETE CASCADE,
    spirit_id NUMBER NULL REFERENCES my_app_spirits(ID) ON DELETE CASCADE,
    quantity NUMBER NOT NULL,
    price NUMBER(6, 2) NULL
);

-- Table: my_app_order
CREATE TABLE my_app_order (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    first_name VARCHAR2(30) NOT NULL,
    last_name VARCHAR2(30) NOT NULL,
    email VARCHAR2(254) NOT NULL,
    phone_number VARCHAR2(15) NOT NULL,
    address VARCHAR2(255) NULL,
    city VARCHAR2(100) NULL,
    county VARCHAR2(100) NOT NULL,
    postal_code VARCHAR2(6) NULL,
    total_price NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pending' NOT NULL
);

-- Table: my_app_orderitem
CREATE TABLE my_app_orderitem (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL REFERENCES my_app_order(id) ON DELETE CASCADE,
    wine_id NUMBER NULL REFERENCES my_app_wines(ID) ON DELETE CASCADE,
    spirit_id NUMBER NULL REFERENCES my_app_spirits(ID) ON DELETE CASCADE,
    quantity NUMBER NOT NULL,
    price NUMBER(6, 2) NOT NULL,
    name VARCHAR2(100) NULL,
    type VARCHAR2(100) NULL,
    year NUMBER NULL,
    grapes VARCHAR2(100) NULL,
    country VARCHAR2(100) NULL,
    region VARCHAR2(100) NULL,
    alcohol_level NUMBER NULL,
    style VARCHAR2(100) NULL
);