# Generated by Django 5.1.3 on 2024-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
