# Generated by Django 5.1.3 on 2024-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_spirits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirits',
            name='Style',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
