# Generated by Django 5.1.3 on 2024-11-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_wines_price_wines_quantity_alter_wines_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wines',
            old_name='id',
            new_name='ID',
        ),
    ]
