# Generated by Django 5.1.3 on 2024-11-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_wines_id_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wines',
        ),
    ]
