# Generated by Django 5.1.3 on 2024-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0006_delete_wines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('grapes', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
