# Generated by Django 5.1.3 on 2024-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_wines_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirits',
            fields=[
                ('Type', models.CharField(default='', max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Style', models.CharField(default='', max_length=100)),
                ('AlcLvl', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Qty', models.IntegerField(null=True)),
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
