# Generated by Django 5.1.3 on 2024-11-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_spirits_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wines',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='grapes',
            new_name='Grapes',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='quantity',
            new_name='Qty',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='year',
            new_name='Year',
        ),
    ]
