# Generated by Django 5.1.3 on 2024-11-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_wines_type_alter_wines_grapes_alter_wines_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='grapes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wines',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wines',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
