# Generated by Django 5.1.3 on 2024-11-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_wines_grapes_alter_wines_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wines',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='grapes',
            new_name='Grapes',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='wines',
            old_name='year',
            new_name='Year',
        ),
    ]
