# Generated by Django 5.1.3 on 2024-11-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_wines_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wines',
            old_name='Quantity',
            new_name='Qty',
        ),
    ]
