# Generated by Django 5.1.3 on 2024-11-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_rename_quantity_wines_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirits',
            name='AlcLvl',
            field=models.IntegerField(default=0),
        ),
    ]
