# Generated by Django 5.1.3 on 2024-11-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_wines_year'),
        ('my_app', '0020_rename_quantity_wines_qty'),
    ]

    operations = [
    ]
