# Generated by Django 5.1.3 on 2024-11-23 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_spirits_alclvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='spirit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.spirits'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.wines'),
        ),
        migrations.AlterField(
            model_name='spirits',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
