# Generated by Django 5.1.3 on 2024-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_cartitem_spirit_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spirits/'),
        ),
        migrations.AddField(
            model_name='wines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wines/'),
        ),
    ]
