# Generated by Django 5.1.3 on 2024-12-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_spirits_image_wines_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='Grapes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wines',
            name='Region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
