# Generated by Django 5.1.3 on 2024-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_alter_spirits_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
