# Generated by Django 5.1.3 on 2024-12-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Price',
            new_name='price',
        ),
    ]
