# Generated by Django 5.1.3 on 2024-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_orderitem_alcohol_level_orderitem_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
