# Generated by Django 5.1.3 on 2024-12-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='spirits',
            field=models.ManyToManyField(related_name='carts', through='my_app.CartItem', to='my_app.spirits'),
        ),
        migrations.AddField(
            model_name='cart',
            name='wines',
            field=models.ManyToManyField(related_name='carts', through='my_app.CartItem', to='my_app.wines'),
        ),
        migrations.AddField(
            model_name='order',
            name='spirits',
            field=models.ManyToManyField(related_name='orders', through='my_app.OrderItem', to='my_app.spirits'),
        ),
        migrations.AddField(
            model_name='order',
            name='wines',
            field=models.ManyToManyField(related_name='orders', through='my_app.OrderItem', to='my_app.wines'),
        ),
    ]
